/* Autogenerated by configure */

#define __dead

#define HAVE_PROGNAME
#define HAVE_ASPRINTF
#define HAVE_PLEDGE
#define HAVE_REALLOCARRAY
#define HAVE_STRLCPY

#define DEBUG

/* unistd.h */
extern char *optarg;
extern int optind;